apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: file-stream-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:asoltes/file-stream-downlod-k8s-config.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: file-stream-app
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
