apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-stream-app
spec:
  replicas: 10
  selector:
    matchLabels:
      app: file-stream-app
  template:
    metadata:
      labels:
        app: file-stream-app
    spec:
      containers:
      - name: file-stream-app
        image: asoltes/file-stream-download:v1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_secret_access_key
